name: Test

run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  test:
    # где запускаем
    runs-on: ubuntu-latest
    # что делаем
    steps:
      # выкачиваем репозиторий
      - uses: actions/checkout@v4

      # установка Chrome и ChromeDriver
      - name: Install Chrome and ChromeDriver
        run: |
          LATEST_CHROMEDRIVER_VERSION=$(curl -sS "https://chromedriver.storage.googleapis.com/LATEST_RELEASE")
          curl -O "https://chromedriver.storage.googleapis.com/$LATEST_CHROMEDRIVER_VERSION/chromedriver_linux64.zip"
          unzip chromedriver_linux64.zip
          chmod +x chromedriver
          sudo mv chromedriver /usr/local/bin/chromedriver
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable=122.0.6261.94-1

      # настраиваем java
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu' # один из дистрибюторов который поставляет джаву
          java-version: '18'

      # запускаем тесты
      - run: ./gradlew clean test